apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/gatekeeper-operator-fbc?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: 'false'
    pipelinesascode.tekton.dev/max-keep-runs: '3'
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: gatekeeper-operator-fbc-4-17
    appstudio.openshift.io/component: gatekeeper-operator-fbc-4-17
    pipelines.appstudio.openshift.io/type: build
  name: gatekeeper-operator-fbc-4-17-on-push
  namespace: gatekeeper-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/gatekeeper-tenant/gatekeeper-operator-fbc-4-17:{{revision}}
    - name: build-platforms
      value:
        - linux/x86_64
        - linux/arm64
        - linux/ppc64le
        - linux/s390x
    - name: dockerfile
      value: catalog.Dockerfile
    - name: path-context
      value: .
    - name: hermetic
      value: 'true'
    - name: build-args
      value:
        - OPM_IMAGE=registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.17
        - INPUT_DIR=catalog-4-17
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/stolostron/konflux-build-catalog.git
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/common-fbc.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-gatekeeper-operator-fbc-4-17
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
