apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/gatekeeper-operator-fbc?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: gatekeeper-operator-fbc
    appstudio.openshift.io/component: gatekeeper-operator-fbc-4-20
    pipelines.appstudio.openshift.io/type: build
  name: gatekeeper-operator-fbc-4-20-on-pull-request
  namespace: gatekeeper-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/gatekeeper-tenant/gatekeeper-operator-fbc-4-20:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: build-platforms
      value:
        - linux/x86_64
    - name: dockerfile
      value: catalog.Dockerfile
    - name: path-context
      value: .
    - name: hermetic
      value: "true"
    - name: build-args
      value:
        - OPM_IMAGE=brew.registry.redhat.io/rh-osbs/openshift-ose-operator-registry-rhel9:v4.20
        - INPUT_DIR=catalog-4-20
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/stolostron/konflux-build-catalog.git
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/common-fbc.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-gatekeeper-operator-fbc-4-20
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
